# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128QhUwMOocmNToeElk51g2GHgwMHJMla
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# tensorflow
# numpy
# Pillow

"""After running the above cell, you'll have a `requirements.txt` file in your Colab environment. Make sure to commit both `app.py` and `requirements.txt` to your GitHub repository for deployment with Streamlit Community Cloud."""

pip install streamlit tensorflow

"""Next, here is the Python code for your Streamlit application. This code will:

1.  Load your `trained_model.h5`.
2.  Provide a file uploader for images.
3.  Preprocess the uploaded image to fit your model's input requirements.
4.  Make a prediction using your CNN model.
5.  Display the uploaded image and the prediction result.

**Please note**: You might need to adjust the image preprocessing steps (e.g., target size, normalization) and the class labels based on how your model was trained.
"""

import streamlit as st
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image
import io

# --- Configuration ---
# Set the path to your trained model
MODEL_PATH = '/content/trained_model.h5'

# Define your class names (replace with your actual class names)
CLASS_NAMES = ['Class_A', 'Class_B', 'Class_C'] # Example: ['dog', 'cat', 'bird']

# Define the target image size for your model (e.g., 224x224 for many CNNs)
TARGET_SIZE = (224, 224)

# --- Load the Model ---
@st.cache_resource # Cache the model to avoid reloading on every rerun
def load_cnn_model():
    try:
        model = tf.keras.models.load_model(MODEL_PATH)
        return model
    except Exception as e:
        st.error(f"Error loading the model: {e}")
        return None

model = load_cnn_model()

# --- Streamlit App Layout ---
st.title('CNN Image Classifier App')
st.write('Upload an image and let the CNN model predict its class!')

if model is None:
    st.stop() # Stop if model failed to load

# --- Image Upload ---
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    image_bytes = uploaded_file.read()
    st.image(image_bytes, caption='Uploaded Image', use_column_width=True)

    # Preprocess the image
    try:
        img = Image.open(io.BytesIO(image_bytes))
        img = img.resize(TARGET_SIZE)
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) # Create a batch dimension

        # Normalize the image pixels (adjust based on your model's training)
        # Common normalizations:
        #   - Divide by 255.0 for pixel values between 0 and 1
        #   - Subtract mean and divide by std dev (if using models like ImageNet pre-trained)
        img_array = img_array / 255.0  # Example: Normalize to [0, 1]

        st.write("Image preprocessing complete. Making prediction...")

        # Make prediction
        predictions = model.predict(img_array)

        # Get the predicted class and probability
        predicted_class_index = np.argmax(predictions, axis=1)[0]
        predicted_probability = np.max(predictions, axis=1)[0]

        predicted_class_name = CLASS_NAMES[predicted_class_index]

        st.success(f"Prediction: **{predicted_class_name}**")
        st.write(f"Confidence: {predicted_probability:.2f}")

        # Optionally display all probabilities
        st.subheader("All Class Probabilities:")
        for i, prob in enumerate(predictions[0]):
            st.write(f"- {CLASS_NAMES[i]}: {prob:.4f}")

    except Exception as e:
        st.error(f"Error processing image or making prediction: {e}")

st.markdown("--- Streamlit App End ---")

"""To run this Streamlit app:

1.  **Save the code** above into a Python file named `app.py` in your Colab environment. You can do this by copying the code block into a new file, for example, by right-clicking in the file browser (left panel) and selecting 'New file'.
2.  Open a new terminal (Tools -> Terminal -> New terminal).
3.  Navigate to the directory where you saved `app.py` (usually `/content/`).
4.  Run the command: `streamlit run app.py`

Streamlit will then provide a local URL (e.g., `http://localhost:8501`) and a public URL for your app. Click on the public URL to access your web application.
"""